# NUMPY ARRAY

In [1]:
import numpy as np

In [2]:
# Check all the functions in numpy
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
np.sqrt(10)

3.1622776601683795

In [4]:
print('Minimum ',np.amin([25,30,57,18]))

print('Maxium ',np.amax([25,30,57,18]))

Minimum  18
Maxium  57


In [5]:
# Rounded off to next number
np.ceil(29.1)

30.0

In [6]:
np.ceil(np.sqrt(10))

4.0

In [7]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

**Similarly there are many numpy functions,you can explore them for your knowledge purpose.But We use limited functions in our  course lit's explore them.**

In [8]:
np.array ([8,9,10])

array([ 8,  9, 10])

In [10]:
xyz = np.array ([8,9,10])

In [9]:
type ([ 8,  9, 10])

list

In [11]:
type(xyz)

numpy.ndarray

In [12]:
# Copy array in to other
b = (np.asarray(xyz))
print(b)

[ 8  9 10]


In [13]:
# dtype converstion
np.array([1, 2, 3], dtype = float)

array([1., 2., 3.])

# two dimensions

In [ ]:
a = np.array ([[1,2], [3,4], [4,5]])
print ('type - ',a.dtype)

In [ ]:
print ('\n' , '*' * 30)  #\n is for next line

print('\n' ,a)

In [ ]:
#dtype conversion
np.array ([1,2,3,4,5,6,7,8,9],dtype = float )


In [ ]:
np.array ([1.0,2.0,3.0] , dtype = int)

In [ ]:
#creating array using .mat(matrix)
np.array (np.mat(' 1 2 3 ; 3 4 5 '))

In [ ]:
# Convert a list in to an array :
a = [1, 2]

c = np.array(a)

print(c)

In [ ]:
#copy array in to others
b = np.asarray(c)
print(b)

##  Data types

In [14]:
my_mat = [[1 ,2 , 3],[4 ,5 , 6,],[7 ,8 , 9]]
mat = np.array(my_mat)

print("Type/ class of this object:",type(mat))

print("Here is the matrix\n----------\n",mat,"\n---------")

print("Dimenson of this matrix: ",mat.ndim,sep=' ')#ndim gives the dimension,2 for a matrix, 1 for a vector

print ("Size of this matrix: ",mat.size ,sep = ' ')  #size gives the total number of elements

print ("Shape of this matrix:",mat.shape)  #shape gives the number of elements along each axis(dimension)

print ("Data type of this matrix: ",mat.dtype)  #dtype gives the data type contained in the array

Type/ class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
---------
Dimenson of this matrix:  2
Size of this matrix:  9
Shape of this matrix: (3, 3)
Data type of this matrix:  int32


### Arange and linspace

In [15]:
# Don't work with python range
list(range(2,9.6,80.4))

TypeError: 'float' object cannot be interpreted as an integer

In [16]:
a = np.arange(2,9.6,0.4)
a

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6, 6. , 6.4, 6.8,
       7.2, 7.6, 8. , 8.4, 8.8, 9.2])

In [17]:
#Reverse order
a[::-1]

array([9.2, 8.8, 8.4, 8. , 7.6, 7.2, 6.8, 6.4, 6. , 5.6, 5.2, 4.8, 4.4,
       4. , 3.6, 3.2, 2.8, 2.4, 2. ])

In [18]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,0,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5]


In [22]:
print("Linerly spaced numbers between 10 and 40 \n--------------------------------------------")
print(np.linspace(10,40,5))

Linerly spaced numbers between 10 and 40 
--------------------------------------------
[10.  17.5 25.  32.5 40. ]


In [23]:
print("Linerly spaced numbers between 10 and 50 \n--------------------------------------------")
print(np.linspace(10,50,10))

Linerly spaced numbers between 10 and 50 
--------------------------------------------
[10.         14.44444444 18.88888889 23.33333333 27.77777778 32.22222222
 36.66666667 41.11111111 45.55555556 50.        ]


In [24]:
#Include end point and check space between the points
# by default endpoint =True
# by default retstep = False
np.linspace(2.0,3.0, num=4, endpoint = False, retstep = True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [26]:
print(np.linspace(4.567867,25.98656,39, retstep = True))

(array([ 4.567867  ,  5.13151682,  5.69516663,  6.25881645,  6.82246626,
        7.38611608,  7.94976589,  8.51341571,  9.07706553,  9.64071534,
       10.20436516, 10.76801497, 11.33166479, 11.89531461, 12.45896442,
       13.02261424, 13.58626405, 14.14991387, 14.71356368, 15.2772135 ,
       15.84086332, 16.40451313, 16.96816295, 17.53181276, 18.09546258,
       18.65911239, 19.22276221, 19.78641203, 20.35006184, 20.91371166,
       21.47736147, 22.04101129, 22.60466111, 23.16831092, 23.73196074,
       24.29561055, 24.85926037, 25.42291018, 25.98656   ]), 0.5636498157894737)


## Matrix creation

In [27]:
print("Vector of zeroes\n-----------------------")

print(np.zeros(8))

Vector of zeroes
-----------------------
[0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
print("Matrix of zeros\n-----------------------------")

print(np.zeros((8,4)))  #Notice Tuples

Matrix of zeros
-----------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
print("Matrix of ones\n-----------------------------")

print(np.ones((4,10))) #Note matrix dimension specified by Tuples

Matrix of ones
-----------------------------
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [30]:
print("Matrix of 5s\n-----------------------------")

print(5*np.ones((4,10)))

Matrix of 5s
-----------------------------
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [31]:
#construct diagonal matrix
x = np.arange(30).reshape (3,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


# Random number generation

In [32]:
import numpy as np

In [33]:
np.random.seed (5)  #each similar number will generate similar data

print ("Random number generation(from uniform distribution)")

print (np.random.rand(10,6))

Random number generation(from uniform distribution)
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]


In [34]:
np.random.seed (4) 

print ("Random number generation(from uniform distribution)")

print (np.random.rand(6,4))

Random number generation(from uniform distribution)
[[0.96702984 0.54723225 0.97268436 0.71481599]
 [0.69772882 0.2160895  0.97627445 0.00623026]
 [0.25298236 0.43479153 0.77938292 0.19768507]
 [0.86299324 0.98340068 0.16384224 0.59733394]
 [0.0089861  0.38657128 0.04416006 0.95665297]
 [0.43614665 0.94897731 0.78630599 0.8662893 ]]


In [35]:
print ("Numbers from Normal Distribution with zero mean and standard deviation 1 i.e.standard normal")

print (np.random.randn(5,4))

Numbers from Normal Distribution with zero mean and standard deviation 1 i.e.standard normal
[[-1.15681626  0.35099715 -0.60688728  1.54697933]
 [ 0.72334161  0.04613557 -0.98299165  0.05443274]
 [ 0.15989294 -1.20894816  2.22336022  0.39429521]
 [ 1.69235772 -1.11281215  1.63574754 -1.36096559]
 [-0.65122583  0.54245131  0.04800625 -2.35807363]]


In [36]:
print ("Random integer vector:")  #randit (low , high ,# of samples to be drawn)

print (np.random.randint(5,20,10))

Random integer vector:
[ 8  5 10 19  9 16 16 16  8 13]


In [37]:
print ("Random integer matrix :")   #randit (low , high ,# of samples to be drawn in a tuple to form a matrix)


print (np.random.randint(1,40000,(6,7)))

Random integer matrix :
[[30537 28923 28542 32311  9887 29061 13577]
 [24037 19346 17487 19582  1733 28421 27560]
 [ 1079 25129 34045 30433  2628  3564 16023]
 [33517 39698 34844  9058 18604 22144 25230]
 [ 2049 29033 12408  2640 25065  9532 14645]
 [22581  6593  5848 11874 19119 24491 33842]]


In [38]:
while True:
    otp1 = np.random.randint(1000,10000,1)
    print ("Ypur otp is - ",otp1)
    user_otp = int(input('Enter otp'))
    if otp1 == user_otp:
        print("Log in success")
        break
    else:
        print("Invalid otp,Generate new otp")
        continue

Ypur otp is -  [6023]
Enter otp6023
Log in success


## Numpy Condition

In [39]:
    # Random integer
a = np.random.randint(1,40, 10)
a

array([36, 31,  2,  4, 23, 11, 21, 17,  8, 11])

In [40]:
# Replace data with fix numbers
np.clip(a, a_min = 10 , a_max = 25)

array([25, 25, 10, 10, 23, 11, 21, 17, 10, 11])

In [41]:
#  it gives index details
print (np.where(a < 10))

(array([2, 3, 8], dtype=int64),)


In [42]:
# Find if data exists in to array

print (np.where( a == 37))

(array([], dtype=int64),)


#### Reshape sort

# Reshaping other ways

In [1]:
import numpy as np
from numpy.random import randint as ri

a = ri(1,99,30)
a

array([95, 79, 98, 89, 19, 59, 85, 66, 38, 13, 92,  4, 16, 53,  3, 95, 70,
       62, 91,  3, 67,  7, 84, 58, 12, 53, 39, 33,  5, 42])

In [12]:
b = a.reshape(2,3,5)
b

array([[[95, 79, 98, 89, 19],
        [59, 85, 66, 38, 13],
        [92,  4, 16, 53,  3]],

       [[95, 70, 62, 91,  3],
        [67,  7, 84, 58, 12],
        [53, 39, 33,  5, 42]]])

In [3]:
c = a.reshape(6,5)
c

array([[95, 79, 98, 89, 19],
       [59, 85, 66, 38, 13],
       [92,  4, 16, 53,  3],
       [95, 70, 62, 91,  3],
       [67,  7, 84, 58, 12],
       [53, 39, 33,  5, 42]])

In [4]:
print ("Min of a:", c.min())

print ("Max of b:", c.max())

Min of a: 3
Max of b: 98


In [5]:
np.mean(c)

51.0

### Sorting

In [15]:
M = ri(1,100,25).reshape(5,5)  # Matrix of random integers
print ("\n 5x5 matrix of random integers\n",'-'*50,"\n",M)

print("\n Here is the sorted matrix along each row \n",'-'*50,"\n",np.sort(M))  #Default axis = 1

print ("\n Here is the sorted matrix along each column \n",'-'*50,"\n",np.sort(M,axis = 0))


 5x5 matrix of random integers
 -------------------------------------------------- 
 [[62 84 38 30 32]
 [ 8 18  2 86 96]
 [22 32 82 26 17]
 [74 39 63 26 76]
 [94 45  9 65 69]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[30 32 38 62 84]
 [ 2  8 18 86 96]
 [17 22 26 32 82]
 [26 39 63 74 76]
 [ 9 45 65 69 94]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[ 8 18  2 26 17]
 [22 32  9 26 32]
 [62 39 38 30 69]
 [74 45 63 65 76]
 [94 84 82 86 96]]


# Indexing and slicing

In [16]:
arr = np.arange(13,30)

print("Array: ",arr)

Array:  [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [17]:
print ("Element at 7th index is:",arr[7])

Element at 7th index is: 20


In [18]:
print ("Element from 3rd to 7th index are: ",arr[3:8])

Element from 3rd to 7th index are:  [16 17 18 19 20]


In [19]:
print ("Elements up to 4th index are:",arr[4:])

Elements up to 4th index are: [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [20]:
abc = arr[4:]  #store the data

In [21]:
arr

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
print("Elements from last backwards are:",arr[-1::-2])

Elements from last backwards are: [29 27 25 23 21 19 17 15 13]


In [23]:
print ("7th Elements from last backwards are:",arr[-1:-8:-1])

7th Elements from last backwards are: [29 28 27 26 25 24 23]


In [24]:
arr = np.arange(0,31,3)
print("new array: ",arr)

new array:  [ 0  3  6  9 12 15 18 21 24 27 30]


In [25]:
print ("Element at 2nd,4th and 9th index are:",arr[[2,4,9]])  #pass a list as a index to subset

Element at 2nd,4th and 9th index are: [ 6 12 27]


In [26]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

mat = np.array(my_mat)

mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print("\n double bracket indexing\n------------------------------------------------")

print("Element in raw index 1 and column index 2:",mat[1][2])


 double bracket indexing
------------------------------------------------
Element in raw index 1 and column index 2: 6


In [28]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print("Entire row at index 2:",mat[2])

print("\n Entire column at index 3: \n",mat[:,1:])

Entire row at index 2: [7 8 9]

 Entire column at index 3: 
 [[2 3]
 [5 6]
 [8 9]]


In [30]:
print("\n subsetting sub matrices\n--------------------------------------------------")

print("Matrix with row indices 1 nd 2 column indices 3 and 4\n",mat[1:2,1:2])


 subsetting sub matrices
--------------------------------------------------
Matrix with row indices 1 nd 2 column indices 3 and 4
 [[5]]


In [31]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print("",mat[0:2,[1,2]])

 [[2 3]
 [5 6]]


# Update Matrix

In [33]:
print("Original matrix \n\n",mat)

Original matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
mat[0,1] = 35
print(mat)

[[ 1 35  3]
 [ 4  5  6]
 [ 7  8  9]]


In [35]:
mat [2,1] = 70
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7, 70,  9]])

# Subseting

In [36]:
mat = np.array(ri(10,100,15).reshape(3,5))

print("mMatrix of random -2 digit numbers \n------------------------------------ \n",mat )

mMatrix of random -2 digit numbers 
------------------------------------ 
 [[69 63 17 35 32]
 [28 16 75 99 68]
 [22 52 99 77 41]]


In [37]:
xyz = mat[mat>70]
xyz

array([75, 99, 99, 77])

In [38]:
print("Elements greater than 50 \n")
mat[mat>50]

Elements greater than 50 



array([69, 63, 75, 99, 68, 52, 99, 77])

In [39]:
print(np.where(mat == 55))

(array([], dtype=int64), array([], dtype=int64))


In [40]:
print(np.where(mat == 86))

(array([], dtype=int64), array([], dtype=int64))


In [53]:
mat >50

array([[ True,  True, False, False, False],
       [False, False,  True,  True,  True],
       [False,  True,  True,  True, False]])

In [54]:
# You can also use np.where to return some data based on condition
marks = 70
np.where(marks >65,'Pass','Fail')

array('Pass', dtype='<U4')

In [56]:
# Check non zeros
non_zeros = ri(-10,50,100)

print(non_zeros)

np.count_nonzero(non_zeros)

[ 39  24   9  -1   5   2  35  -8  33  -7  35  19  27  31  -1  28  20   2
   6  36  44  17 -10  26  33  42  -6   8  37  41   8  -9   6  35  29  37
  13  18  39  25  38  14  -4  14  -4  -3   8  36  39  44   1  30  40  12
   2  18  30  17   0  22  37  43  33   8  38  16  -2  18  22  27  -7  17
  24   4  48  -5  18  47   9   0  48  35  17  -2  31  -5  -9   6  14  49
   9   1   4  37   2  49  36  20  49  42]


98

In [59]:
# Ravel or Flatten (This concept is used in deep learning for image processing)
array = np.random.randint(0, 20, size = (3, 4))
print(array)

array.ravel()

[[ 1 17  6  3]
 [14 15  0 19]
 [13  3 10  9]]


array([ 1, 17,  6,  3, 14, 15,  0, 19, 13,  3, 10,  9])

In [60]:
# or Flatten both are same
array.flatten()

array([ 1, 17,  6,  3, 14, 15,  0, 19, 13,  3, 10,  9])

# Universal function

In [41]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)

mat2 = np.array(ri(1,10,9)).reshape(3,3)


print("\n 1st matrix of random single - digit numbers \n-------------------------------\n",mat1)

print("\n 2nd matrix of random single - digit numbers \n-------------------------------\n",mat2)


 1st matrix of random single - digit numbers 
-------------------------------
 [[1 9 2]
 [1 9 6]
 [4 9 8]]

 2nd matrix of random single - digit numbers 
-------------------------------
 [[5 7 8]
 [9 3 2]
 [5 5 5]]


In [42]:
print("mat1 = \n",mat1)
print("mat2 = \n",mat2)

mat1 = 
 [[1 9 2]
 [1 9 6]
 [4 9 8]]
mat2 = 
 [[5 7 8]
 [9 3 2]
 [5 5 5]]


In [64]:
print("\n division \n---------------------------------------\n",mat1/mat2)

print("\n Liner combination: 3*A -2*B \n-----------------------------------------\n",      3*mat1 - 2*mat2)


 division 
---------------------------------------
 [[1.         6.         0.66666667]
 [0.375      1.         0.375     ]
 [0.5        2.5        0.88888889]]

 Liner combination: 3*A -2*B 
-----------------------------------------
 [[ 9 16  0]
 [-7  5 -7]
 [-3 11  6]]


In [62]:
print('\n Addition \n***************************\n',             mat1+mat2)              


 Addition 
***************************
 [[18  7 10]
 [11 10 11]
 [ 9  7 17]]


# Broadcasting

In [44]:
start = np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
# create a rank 1 ndarray with 3 values
add_rows =np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [46]:
y = start + add_rows  #add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [47]:
new_rows = add_rows.T
new_rows

array([[1],
       [0],
       [2]])

In [48]:
test = new_rows + start
print(test)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]


In [49]:
#create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[[0,1,2,3]]])

add_cols = add_cols.T

add_cols

array([[[0]],

       [[1]],

       [[2]],

       [[3]]])

## Array Math

In [50]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st matrix of random single-digit numbers \n--------------------------------------------\n"),mat1
print("\n 2nd matrix of random single-digit numbers \n--------------------------------------------\n"),mat2


 1st matrix of random single-digit numbers 
--------------------------------------------


 2nd matrix of random single-digit numbers 
--------------------------------------------



(None,
 array([[9, 1, 6],
        [8, 5, 8],
        [6, 2, 9]]))

In [51]:
print("\n sq-root of 1st matrix using np\n----------------------------------------------\n"),np.sqrt(mat1)




 sq-root of 1st matrix using np
----------------------------------------------



(None,
 array([[3.        , 2.44948974, 2.        ],
        [1.73205081, 2.23606798, 1.73205081],
        [1.73205081, 2.23606798, 2.82842712]]))

In [52]:
print("\n square of 1st matrix using np\n----------------------------------------------\n"),np.square(mat1)


 square of 1st matrix using np
----------------------------------------------



(None,
 array([[81, 36, 16],
        [ 9, 25,  9],
        [ 9, 25, 64]], dtype=int32))